/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-08 20:45:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Producto;
import service.Dao_Producto;
import java.util.Optional;
import java.util.List;
import db.ConexionSingleton;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Layouts/nav.jsp", Long.valueOf(1717871494761L));
    _jspx_dependants.put("/Layouts/footer.jsp", Long.valueOf(1717869919992L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("service.Dao_Producto");
    _jspx_imports_classes.add("java.util.Optional");
    _jspx_imports_classes.add("db.ConexionSingleton");
    _jspx_imports_classes.add("model.Producto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("        <title>Crud Java Web</title>\r\n");
      out.write("        <!-- Material Icon CDN -->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- Materialize CSS CDN -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css\">\r\n");
      out.write("        <!-- Your custom styles -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- Used as an example only to position the footer at the end of the page.\r\n");
      out.write("        You can delete these styles or move it to your custom css file -->\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("            main {\r\n");
      out.write("                flex: 1 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <header>\r\n");
      out.write("            <nav class=\"cyan\">\r\n");
      out.write("                <div class=\"nav-wrapper\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <a href=\"#\" class=\"brand-logo\">Productos</a>\r\n");
      out.write("                        <a href=\"#\" data-activates=\"mobile-menu\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                        <ul class=\"right hide-on-med-and-down\">\r\n");
      out.write("                            <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul class=\"side-nav\" id=\"mobile-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"userView\">\r\n");
      out.write("                                    <div class=\"background\">\r\n");
      out.write("                                        <img src=\"http://lorempixel.com/output/abstract-q-c-640-480-10.jpg\" alt=\"Background Sidenav\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <a href=\"#!user\"><img class=\"circle\" src=\"http://lorempixel.com/output/people-q-c-640-480-9.jpg\" alt=\"User Image Sidenav\"></a>\r\n");
      out.write("                                    <a href=\"#!name\"><span class=\"white-text name\">John Doe</span></a>\r\n");
      out.write("                                    <a href=\"#!email\"><span class=\"white-text email\">jdandturk@gmail.com</span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">item1</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("        ");
ConexionSingleton oConexionSingleton = ConexionSingleton.getIntance();
      out.write("\r\n");
      out.write("        <main>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12 m6 l6\">\r\n");
      out.write("                        <div class=\"card-panel\">\r\n");
      out.write("                            <div class=\"card-content\">\r\n");
      out.write("                                <h4>Crear Producto</h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <form action=\"insertProduct\" method=\"post\" class=\"col s12\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"input-field col s6\">\r\n");
      out.write("                                                    <input id=\"nombre\" name=\"nombre\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                    <label for=\"nombre\">Nombre</label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"input-field col s6\">\r\n");
      out.write("                                                    <input id=\"descripcion\" name=\"descripcion\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                    <label for=\"descripcion\">Descripcion</label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"input-field col s6\">\r\n");
      out.write("                                                    <input id=\"precio\" name=\"precio\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                    <label for=\"precio\">Precio</label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <button type=\"submit\" class=\"waves-effect waves-light btn\">Crear</button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!--<img src=\"IMG/Create.jpg\">-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col s12 m6 l6\">\r\n");
      out.write("                        <div class=\"card-panel\">\r\n");
      out.write("                            <div class=\"card-content\">\r\n");
      out.write("                                <h4>Lista de Productos</h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <table class = \"striped responsive-table\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>ID</th>\r\n");
      out.write("                                                <th>Nombre</th>\r\n");
      out.write("                                                <th>Descripción</th>\r\n");
      out.write("                                                <th>Precio</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            ");

                                                Dao_Producto oDao_Producto = new Dao_Producto(oConexionSingleton);
                                                List<Producto> oList = oDao_Producto.getAll().get();
                                                for (Producto oProducto : oList) {
                                            
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>");
      out.print( oProducto.getId());
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( oProducto.getNombre());
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( oProducto.getDescripcion());
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( oProducto.getPrecio());
      out.write("</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <!--<img src=\"IMG/Read.jpg\">-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12 m6 l6\">\r\n");
      out.write("                        <div class=\"card-panel\">\r\n");
      out.write("                            <div class=\"card-content\">\r\n");
      out.write("                                <h4>Actualizar Productos</h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <form action=\"updateProduct\" method=\"post\" class=\"col s12\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"input-field col s6\">\r\n");
      out.write("                                                <input id=\"id\" name=\"id\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                <label for=\"id\">ID</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"input-field col s6\">\r\n");
      out.write("                                                <input id=\"nombre\" name=\"nombre\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                <label for=\"nombre\">Nombre</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"input-field col s6\">\r\n");
      out.write("                                                <input id=\"descripcion\" name=\"descripcion\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                <label for=\"descripcion\">Descripcion</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"input-field col s6\">\r\n");
      out.write("                                                <input id=\"precio\" name=\"precio\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                <label for=\"precio\">Precio</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button type=\"submit\" class=\"waves-effect waves-light btn\">Actualizar</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col s12 m6 l6\">\r\n");
      out.write("                        <div class=\"card-panel\">\r\n");
      out.write("                            <div class=\"card-content\">\r\n");
      out.write("                                <h4>Eliminar Producto</h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <form action=\"deleteProduct\" method=\"post\" class=\"col s12\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"input-field col s6\">\r\n");
      out.write("                                                <input id=\"id\" name=\"id\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                                <label for=\"id\">ID</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button type=\"submit\" class=\"waves-effect waves-light btn\">Eliminar</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--<img src=\"IMG/Delete.jpg\">-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <footer class=\"page-footer cyan\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12 m8 l6\">\r\n");
      out.write("                        <h5 class=\"white-text\">First Footer Content</h5>\r\n");
      out.write("                        <p class=\"grey-text text-lighten-4\">You can use rows and columns here to organize your footer content.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col s12 m4 l6\">\r\n");
      out.write("                        <h5 class=\"white-text\">Second Footer Content</h5>\r\n");
      out.write("                        <p class=\"grey-text text-lighten-4\">You can use rows and columns here to organize your footer content.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-copyright\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    © 2017 Copyright Text\r\n");
      out.write("                    <a class=\"grey-text text-lighten-4 right\" href=\"#!\">More Links</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("        <!-- jQuery CDN -->\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\" integrity=\"sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Materialize JS CDN -->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js\"></script>\r\n");
      out.write("        <!--  <script src=\"JS/validarut.js\"></script>\r\n");
      out.write("        <script src=\"JS/jquery.rut.js\"></script>-->\r\n");
      out.write("        <!--  <script>\r\n");
      out.write("            $(\"document\").ready(function () {\r\n");
      out.write("                $(\".button-collapse\").sideNav();\r\n");
      out.write("            });\r\n");
      out.write("            $(function () {\r\n");
      out.write("                $(\"input#rut_Profe\").rut({\r\n");
      out.write("                    formatOn: 'keyup',\r\n");
      out.write("                    minimumLength: 8, // validar largo mínimo; default: 2\r\n");
      out.write("                    validateOn: 'change' // si no se quiere validar, pasar null\r\n");
      out.write("                });\r\n");
      out.write("                var input = document.getElementById('rut_Profe');\r\n");
      out.write("                input.addEventListener('input', function () {\r\n");
      out.write("                    if (this.value.length >= 13)\r\n");
      out.write("                        this.value = this.value.slice(0, 12);\r\n");
      out.write("                })\r\n");
      out.write("            });\r\n");
      out.write("        </script>-->\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
