/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-12 05:54:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Usuario;
import service.DAOUsuario;
import db.Conexion;
import java.util.Optional;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Layouts/nav.jsp", Long.valueOf(1717647929000L));
    _jspx_dependants.put("/Layouts/footer.jsp", Long.valueOf(1717647929000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("service.DAOUsuario");
    _jspx_imports_classes.add("java.util.Optional");
    _jspx_imports_classes.add("model.Usuario");
    _jspx_imports_classes.add("db.Conexion");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("        <title>Crud Java Web</title>\n");
      out.write("        <!-- Material Icon CDN -->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n");
      out.write("        <!-- Materialize CSS CDN -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css\">\n");
      out.write("        <!-- Your custom styles -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n");
      out.write("        <!-- Used as an example only to position the footer at the end of the page.\n");
      out.write("        You can delete these styles or move it to your custom css file -->\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                display: flex;\n");
      out.write("                min-height: 100vh;\n");
      out.write("                flex-direction: column;\n");
      out.write("            }\n");
      out.write("            main {\n");
      out.write("                flex: 1 0 auto;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header>\n");
      out.write("            <nav class=\"cyan\">\n");
      out.write("                <div class=\"nav-wrapper\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <a href=\"#\" class=\"brand-logo\">LOGO</a>\n");
      out.write("                        <a href=\"#\" data-activates=\"mobile-menu\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\n");
      out.write("                        <ul class=\"right hide-on-med-and-down\">\n");
      out.write("                            <li><a href=\"#\">item1</a></li>\n");
      out.write("                            <li><a href=\"#\">item2</a></li>\n");
      out.write("                            <li><a href=\"#\">item3</a></li>\n");
      out.write("                            <li><a href=\"#\">item4</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                        <ul class=\"side-nav\" id=\"mobile-menu\">\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"userView\">\n");
      out.write("                                    <div class=\"background\">\n");
      out.write("                                        <img src=\"http://lorempixel.com/output/abstract-q-c-640-480-10.jpg\" alt=\"Background Sidenav\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <a href=\"#!user\"><img class=\"circle\" src=\"http://lorempixel.com/output/people-q-c-640-480-9.jpg\" alt=\"User Image Sidenav\"></a>\n");
      out.write("                                    <a href=\"#!name\"><span class=\"white-text name\">John Doe</span></a>\n");
      out.write("                                    <a href=\"#!email\"><span class=\"white-text email\">jdandturk@gmail.com</span></a>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"#\">item1</a></li>\n");
      out.write("                            <li><a href=\"#\">item2</a></li>\n");
      out.write("                            <li><a href=\"#\">item3</a></li>\n");
      out.write("                            <li><a href=\"#\">item4</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("        ");
Conexion conn = Conexion.getIntance();
      out.write("\n");
      out.write("        <main>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col s12 m6 l6\">\n");
      out.write("                        <div class=\"card-panel\">\n");
      out.write("                            <div class=\"card-content\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <form action=\"insertarUsuario\" method=\"post\" class=\"col s12\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"input-field col s6\">\n");
      out.write("                                                    <input name=\"nombre\" type=\"text\" class=\"validate\" required>\n");
      out.write("                                                    <label for=\"nombre\">Nombre</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"input-field col s6\">\n");
      out.write("                                                    <input name=\"apellido\" type=\"text\" class=\"validate\" required>\n");
      out.write("                                                    <label for=\"apellido\">Apellido</label>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"input-field col s6\">\n");
      out.write("                                                    <input name=\"correo\" type=\"text\" class=\"validate\" required>\n");
      out.write("                                                    <label for=\"correo\">Correo</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"input-field col s6\">\n");
      out.write("                                                    <input name=\"direccion\" type=\"text\" class=\"validate\" required>\n");
      out.write("                                                    <label for=\"direccion\">Direccion</label>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            <button type=\"submit\" class=\"waves-effect waves-light btn\">Insertar</button>\n");
      out.write("                                        </form>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!--<img src=\"IMG/Create.jpg\">-->\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col s12 m6 l6\">\n");
      out.write("                        <div class=\"card-panel\">\n");
      out.write("                            <div class=\"card-content\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <table class = \"striped responsive-table\">\n");
      out.write("                                        <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th>ID</th>\n");
      out.write("                                                <th>Nombre</th>\n");
      out.write("                                                <th>Apellido</th>\n");
      out.write("                                                <th>Correo</th>\n");
      out.write("                                                <th>Direccion</th>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </thead>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            ");

                                                DAOUsuario oDAOUsuario = new DAOUsuario(conn);
                                                List<Usuario> oLista = oDAOUsuario.getAll().get();
                                                for (Usuario oUsuario : oLista) {
                                            
      out.write("\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>");
      out.print( oUsuario.getId());
      out.write("</td>\n");
      out.write("                                                <td>");
      out.print( oUsuario.getNombre());
      out.write("</td>\n");
      out.write("                                                <td>");
      out.print( oUsuario.getApellido());
      out.write("</td>\n");
      out.write("                                                <td>");
      out.print( oUsuario.getCorreo());
      out.write("</td>\n");
      out.write("                                                <td>");
      out.print( oUsuario.getDireccion());
      out.write("</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                    <!--<img src=\"IMG/Read.jpg\">-->\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("        </main>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <footer class=\"page-footer cyan\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col s12 m8 l6\">\n");
      out.write("                        <h5 class=\"white-text\">First Footer Content</h5>\n");
      out.write("                        <p class=\"grey-text text-lighten-4\">You can use rows and columns here to organize your footer content.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col s12 m4 l6\">\n");
      out.write("                        <h5 class=\"white-text\">Second Footer Content</h5>\n");
      out.write("                        <p class=\"grey-text text-lighten-4\">You can use rows and columns here to organize your footer content.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-copyright\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    © 2017 Copyright Text\n");
      out.write("                    <a class=\"grey-text text-lighten-4 right\" href=\"#!\">More Links</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("        <!-- jQuery CDN -->\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\" integrity=\"sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <!-- Materialize JS CDN -->\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js\"></script>\n");
      out.write("        <script src=\"JS/validarut.js\"></script>\n");
      out.write("        <script src=\"JS/jquery.rut.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            $(\"document\").ready(function () {\n");
      out.write("                $(\".button-collapse\").sideNav();\n");
      out.write("            });\n");
      out.write("            $(function () {\n");
      out.write("                $(\"input#rut_Profe\").rut({\n");
      out.write("                    formatOn: 'keyup',\n");
      out.write("                    minimumLength: 8, // validar largo mínimo; default: 2\n");
      out.write("                    validateOn: 'change' // si no se quiere validar, pasar null\n");
      out.write("                });\n");
      out.write("                var input = document.getElementById('rut_Profe');\n");
      out.write("                input.addEventListener('input', function () {\n");
      out.write("                    if (this.value.length >= 13)\n");
      out.write("                        this.value = this.value.slice(0, 12);\n");
      out.write("                })\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
